# This rule is not used by the project argon itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to argon.argon.github.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argon
    app.kubernetes.io/managed-by: kustomize
  name: argonconfig-viewer-role
rules:
- apiGroups:
  - argon.argon.github.io
  resources:
  - argonconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argon.argon.github.io
  resources:
  - argonconfigs/status
  verbs:
  - get
