---
apiVersion: rbac.yaml.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argon.argon.github.io
  resources:
  - ingress
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argon.argon.github.io
  resources:
  - ingress/finalizers
  verbs:
  - update
- apiGroups:
  - argon.argon.github.io
  resources:
  - ingress/status
  verbs:
  - get
  - patch
  - update
