# .cargo/config.toml
[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static"]

[target.aarch64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-static"]
