apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
        imagePullPolicy: IfNotPresent
        args:
          - --provider=oidc
          # Use the public issuer, exposed via Ingress
          - --oidc-issuer-url=http://dex.local:8080/dex
          - --client-id=oauth2-proxy
          - --email-domain=*
          - --http-address=0.0.0.0:4180
          - --reverse-proxy=true
          - --set-xauthrequest=true
          - --skip-provider-button=true
          - --cookie-secure=false
          - --cookie-samesite=lax
          - --redirect-url=http://echo.local/oauth2/callback
        env:
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy
                key: cookie-secret
        ports:
          - name: http
            containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  selector:
    app: oauth2-proxy
  ports:
    - name: http
      port: 4180
      targetPort: 4180
